# Generated by Django 3.2.4 on 2021-06-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('stock_pcs', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shop_id', models.CharField(max_length=100)),
                ('vip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shop_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.product')),
            ],
        ),
    ]
