version: "3.7"
services:
  shop:
    image: harbor.chlin.tk/python/shop:latest
    container_name: shop
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ~/etc/timezone:/etc/localtime:ro
    restart: always
    command: python manage.py runserver 0.0.0.0:9000
    ports: 
      - 9000:9000