version: "3.7"
services:
  web:
    image: ${DOCKER_IMAGE}
    container_name: shop
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ~/etc/timezone:/etc/localtime:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - ${PORT}:${PORT}
    env_file:
      - ${ENV}
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:${PORT}/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s